CREATE TABLE urls (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255) NOT NULL,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS url_checks (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          url_id BIGINT NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
    status_code INT,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_url_checks_url_id ON url_checks(url_id);